spring:
  datasource:
    url: jdbc:mysql://%{你的数据库地址}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: %{你的数据库账户名}
    password: %{你的数据库密码}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 100000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      connection-init-sql: set names utf8mb4;
    leuth:
      sampler:
        percentage: 1

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  max-time: 1000
mybatis-plus:
  type-aliases-package: com.kkb.**.entity
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dingtalk:
  app:
    key: %{你的钉钉AppKey}
    secret: %{你的钉钉AppSecret}

server:
  servlet:
    context-path: /temperature
